name: ${COMPOSE_PROJECT_NAME}
services:
  quizzer:
    image: macchiato23/quizzer:0.0.2-SNAPSHOT
    environment:
      DATABASE_HOST: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - postgres
    ports:
      - "8180:8080"
    depends_on:
      - postgres
  kafka-1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-1
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: "WnLkTHhkQaiJbwP8FClPhw"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9091
      KAFKA_LISTENERS: PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9090, EXTERNAL://${HOSTNAME:-localhost}:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka-1-data:/var/lib/kafka/data
      - ./kafka/server.properties:/opt/kafka/config/server.properties
    networks:
      - kafka-net
    restart: unless-stopped

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER:-default}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_DB: ${DATABASE_NAME:-edupulse}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - '${DATABASE_PORT:-5432}:5432'
    networks:
      - postgres
    restart: unless-stopped

networks:
  kafka-net:
    driver: bridge
    external: true
    name: kafka-broker-net
  postgres:
    driver: bridge
    external: true
    name: postgres

volumes:
  kafka-1-data:
  postgres: