name: edupulse
services:
  ingest:
    image: us-central1-docker.pkg.dev/edupulse-483220/edupulse/event-ingest-service:0.0.1-SNAPSHOT
    env_file:
      - ../../.env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      SCHEMA_REGISTRY_URL: ${SCHEMA_REGISTRY_URL}
      SCHEMA_REGISTRY_API_KEY: ${SCHEMA_REGISTRY_API_KEY}
      SCHEMA_REGISTRY_API_SECRET: ${SCHEMA_REGISTRY_API_SECRET}
      KAFKA_API_KEY: ${KAFKA_API_KEY}
      KAFKA_API_SECRET: ${KAFKA_API_SECRET}
      SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL: SASL_SSL
      SPRING_KAFKA_PROPERTIES_SASL_MECHANISM: PLAIN
      SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username='${KAFKA_API_KEY}' password='${KAFKA_API_SECRET}';
      APP_CLIENTS_QUIZZER_URL: http://quizzer:8080
    networks:
      - postgres
      - microservice
      - kafka-net
    ports:
      - "8081:8080"
    depends_on:
      - postgres

  quizzer:
    image: us-central1-docker.pkg.dev/edupulse-483220/edupulse/quizzer:0.0.2-SNAPSHOT
    env_file:
      - ../../.env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      GCP_REGION: ${REGION}
      GCP_PROJECT_ID: ${PROJECT_ID}
    volumes:
      - ${GCP_CREDENTIALS_PATH:-../secure/vertex-ai-credentials.json}:/app/config/gcp-credentials.json:ro
    networks:
      - postgres
      - microservice
      - kafka-net
    ports:
      - "8082:8080"
    depends_on:
      - postgres

  redis:
    image: redis
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - redis
    restart: unless-stopped

  kafka-1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-1
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: "WnLkTHhkQaiJbwP8FClPhw"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9091
      KAFKA_LISTENERS: PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9090, EXTERNAL://${HOSTNAME:-localhost}:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka-1-data:/var/lib/kafka/data
      - ./kafka/server.properties:/opt/kafka/config/server.properties
    networks:
      - kafka-net
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine3.19
    environment:
      POSTGRES_USER: ${DATABASE_USER:-default}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_DB: ${DATABASE_NAME:-edupulse}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - '${DATABASE_PORT:-5432}:5432'
    networks:
      - postgres
    restart: unless-stopped

networks:
  microservice:
    driver: bridge
  kafka-net:
    driver: bridge
    external: true
    name: kafka-broker-net
  postgres:
    driver: bridge
    external: true
    name: postgres
  redis:
    driver: bridge
    external: true
    name: redis

volumes:
  kafka-1-data:
  postgres: